# =====================================================================
# Restore Visual Studio 2026 Defaults (Undo Optimization Script)
# PowerShell 7 Recommended
# =====================================================================

Write-Host "=== Restoring Visual Studio 2026 Defaults ===" -ForegroundColor Cyan

# ---------------------------------------------------------------------------
# PART 1 — No-op for Caches (they were only cleared)
# ---------------------------------------------------------------------------
Write-Host "`n=== Visual Studio Caches ===" -ForegroundColor Yellow
Write-Host "No restoration needed: caches were only deleted and will be regenerated by Visual Studio." -ForegroundColor Green

# ---------------------------------------------------------------------------
# PART 2 — Re-enable CodeLens
# ---------------------------------------------------------------------------
Write-Host "`n=== Re-enabling CodeLens ===" -ForegroundColor Yellow

$regPath = "HKCU:\Software\Microsoft\VisualStudio\17.0\CodeLens"
if (Test-Path $regPath) {
    # Default: 1 (enabled)
    Set-ItemProperty -Path $regPath -Name "EnableCodeLens" -Value 1 -ErrorAction SilentlyContinue
    Write-Host "CodeLens re-enabled." -ForegroundColor Green
}
else {
    Write-Host "CodeLens key not found; nothing to restore." -ForegroundColor DarkYellow
}

# ---------------------------------------------------------------------------
# PART 3 — Re-enable Full Solution Analysis
# ---------------------------------------------------------------------------
Write-Host "`n=== Re-enabling Full Solution Analysis ===" -ForegroundColor Yellow

$analysisPath = "HKCU:\Software\Microsoft\VisualStudio\17.0\Roslyn\Internal\Performance"
if (Test-Path $analysisPath) {
    # Default: 1 (enabled) for full solution analysis
    Set-ItemProperty -Path $analysisPath -Name "FullSolutionAnalysis" -Value 1 -ErrorAction SilentlyContinue
    Write-Host "Full Solution Analysis re-enabled." -ForegroundColor Green
}
else {
    Write-Host "Roslyn performance key not found; nothing to restore." -ForegroundColor DarkYellow
}

# ---------------------------------------------------------------------------
# PART 4 — Re-enable Live Share
# ---------------------------------------------------------------------------
Write-Host "`n=== Re-enabling Live Share ===" -ForegroundColor Yellow

$liveSharePath = "HKCU:\Software\Microsoft\VisualStudio\17.0\LiveShare"
if (Test-Path $liveSharePath) {
    # Default: 1 (enabled)
    Set-ItemProperty -Path $liveSharePath -Name "EnableLiveShare" -Value 1 -ErrorAction SilentlyContinue
    Write-Host "Live Share re-enabled." -ForegroundColor Green
}
else {
    Write-Host "Live Share key not found; nothing to restore." -ForegroundColor DarkYellow
}

# ---------------------------------------------------------------------------
# PART 5 — Handle Directory.Build.props created by optimization script
# ---------------------------------------------------------------------------
Write-Host "`n=== Handling Directory.Build.props ===" -ForegroundColor Yellow

$propsPath = "$env:USERPROFILE\source\repos\Directory.Build.props"

if (Test-Path $propsPath) {
    $content = Get-Content -Path $propsPath -Raw -ErrorAction SilentlyContinue

    $marker = @"
<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>false</ContinuousIntegrationBuild>
    <UseSharedCompilation>true</UseSharedCompilation>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <ProduceReferenceAssembly>false</ProduceReferenceAssembly>
  </PropertyGroup>
</Project>
"@

    if ($content -replace '\s+', '' -eq $marker -replace '\s+', '') {
        Write-Host "Directory.Build.props matches the optimization script's content. Removing it..." -ForegroundColor Yellow
        Remove-Item -Path $propsPath -Force -ErrorAction SilentlyContinue
        Write-Host "Directory.Build.props removed." -ForegroundColor Green
    }
    else {
        Write-Host "Directory.Build.props exists but does not match the optimization script's content. Leaving it untouched." -ForegroundColor DarkYellow
    }
}
else {
    Write-Host "Directory.Build.props not found; nothing to remove." -ForegroundColor DarkYellow
}

# ---------------------------------------------------------------------------
# PART 6 — Re-enable Visual Studio Telemetry
# ---------------------------------------------------------------------------
Write-Host "`n=== Re-enabling Visual Studio Telemetry ===" -ForegroundColor Yellow

$telemetryPath = "HKCU:\Software\Microsoft\VisualStudio\17.0\Telemetry"
if (Test-Path $telemetryPath) {
    # Default: 0 (telemetry allowed)
    Set-ItemProperty -Path $telemetryPath -Name "TurnOffSwitch" -Value 0 -ErrorAction SilentlyContinue
    Write-Host "Visual Studio telemetry re-enabled." -ForegroundColor Green
}
else {
    Write-Host "Telemetry key not found; nothing to restore." -ForegroundColor DarkYellow
}

# ---------------------------------------------------------------------------
# Done
# ---------------------------------------------------------------------------
Write-Host "`n=== Visual Studio Defaults Restore Complete ===" -ForegroundColor Cyan
Write-Host "Restart Visual Studio to apply all changes." -ForegroundColor Yellow